### ISSUE TITLE
CSS url() imports breaking

### ISSUE THREAD

**Issue by phaistonian** [slightlyfaulty/stylus-native-loader#1]
`@import url('https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:400,500,600,700&display=swap&subset=greek');`

This kind of breaks.

Replacing single quotes to double ones would probably fix it, but I did not get there yet.

**Comment by slightlyfaulty** [comment]
Thanks for the bug report. The issue was due to the custom `AliasEvaluator` getting caught out by the url() import. This is now fixed in v1.0.3.

(Apologies for the commit spam - it's my first repo 🙈)

**Comment by phaistonian** [comment]
Thank you.

There seems to be an issue related to this loader working with [mini css extract plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) but I have not got the time to figure out what's the issue exactly.

If I get some time, I will come back with a new issue.

**Comment by slightlyfaulty** [comment]
Hmm that's weird. I'm using `mini-css-extract-plugin` with this loader on a separate project with no problem.

Feel free to just drop your webpack config and any errors you're getting on a new issue and I'll be happy to check it out.
